[tools]
bun = "latest"

[tasks.build]
alias = "b"
description = "Production build"
run = "tsdown"

[tasks.start]
description = "Start the language server (production)"
run = "node dist/cli.js --stdio"
depends = ["build"]

[tasks.start-bun]
description = "Start the language server with bun (production)"
run = "bun --bun dist/cli.js --stdio"
depends = ["build"]

[tasks.dev]
alias = "d"
description = "Dev server"
run = "bun run --watch src/cli.ts --stdio"
