[tools]
bun = "latest"

[tasks.build]
alias = "b"
description = "Production build"
run = "tsdown"

[tasks.package]
depends = ["build"]
run = "bun vsce package"

[tasks.build-debug]
description = "Debug build"
run = "tsdown --minify=false --sourcemap"
